.

diff --git a/raw/bin/kmn b/raw/bin/kmn
--- a/raw/bin/kmn
+++ b/raw/bin/kmn
@@ -1,12 +1,34 @@
 #! /bin/bash
 # https://github.com/shakibamoshiri/bash-CLI-template
 
+################################################################################
+# bash strict mode
+################################################################################
+
+set -T # inherit DEBUG and RETURN trap for functions
+set -C # prevent file overwrite by > &> <>
+set -E # inherit -e
+set -e # exit immediately on errors
+set -u # exit on not assigned variables
+set -o pipefail # exit on pipe failure
+
+################################################################################
+# environment
+################################################################################
 APP_DIR="${KMN_DIR}"
 APP_DIR="${APP_DIR}" . "${APP_DIR}/app/env"
 
-function __add() (
+################################################################################
+# global variable
+################################################################################
+declare -r ERR_MSG="Error: a value is needed for '$1'";
 
-  ################################################################################
+################################################################################
+# functions
+################################################################################
+
+function __add() (
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -27,7 +49,7 @@ function __add() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
 
   local pubkey_path="${HOME}/.ssh/${opts[KEY_NAME]}.pub"
@@ -45,7 +67,7 @@ function __add() (
 
 function __keygen() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -67,7 +89,7 @@ function __keygen() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
 
   local key_priv_path="${HOME}/.ssh/${opts[KEY_NAME]}"
@@ -89,7 +111,7 @@ function __keygen() (
 
 function __copy() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -111,7 +133,7 @@ function __copy() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
   local gh_baseurl="https://raw.githubusercontent.com/${opts[PUBKEY_USERNAME]}/${PUBKEY_REPO}/master"
   local gh_key_url="${gh_baseurl}/pub/${opts[KEY_NAME]}.pub"
@@ -123,7 +145,7 @@ function __copy() (
 
 function __git_config() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -144,7 +166,7 @@ function __git_config() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
   # TODO: for windows '"C:/Program Files/OpenSSH/ssh.exe"'
   # TODO: or better for windows: where.exe ssh.exe
@@ -160,7 +182,7 @@ function __git_config() (
 
 function __github_auth() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -180,7 +202,7 @@ function __github_auth() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
   # github.com/login/device
   # --git-protocol does not change how you login, it changes how subsequent git operations are handled
@@ -199,7 +221,7 @@ function __github_auth() (
 
 function __github_ssh() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -219,7 +241,7 @@ function __github_ssh() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
   pubkey_path="${HOME}/.ssh/${opts[KEY_NAME]}.pub"
 
@@ -231,7 +253,7 @@ function __github_ssh() (
 
 function __setup_mkays() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
   function parse_opts() {
 
@@ -253,7 +275,7 @@ function __setup_mkays() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
   repo_ssl="https://github.com/${opts[PUBKEY_USERNAME]}/${opts[PUBKEY_REPO]}.git"
   repo_ssh="git@github.com:${opts[PUBKEY_USERNAME]}/${opts[PUBKEY_REPO]}.git"
@@ -272,7 +294,7 @@ function __setup_mkays() (
 
 function main() (
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # arguments
 
   function parse_opts() {
@@ -294,10 +316,10 @@ function main() (
   declare -A opts
   parse_opts $@
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # body
 
-  ################################################################################
+#-----------------------------------------------------------------------------
   # caller
 
   if (( ${#} == 0 )); then
@@ -309,6 +331,10 @@ function main() (
     keygen ) __keygen "${args[@]:1}" ;;
     add ) __add "${args[@]:1}" ;;
     copy ) __copy "${args[@]:1}" ;;
+    git-config ) __git_config "${args[@]:1}" ;;
+    github-auth ) __github_auth "${args[@]:1}" ;;
+    github-ssh ) __github_ssh "${args[@]:1}" ;;
+    setup-mkays __setup_mkays "${args[@]:1}" ;;
     * )
       echo >&2 "Unknown command: $1";
       # main_help 1;
