.

diff --git a/raw/bin/kmn b/raw/bin/kmn
--- a/raw/bin/kmn
+++ b/raw/bin/kmn
@@ -1,35 +1,96 @@
 #! /bin/bash
-
-kmn__test() {
-  ${BIN_DIR}/kmn-test
-  echo ok
-}
-
-kmn() {
+# https://github.com/shakibamoshiri/bash-CLI-template
 
   APP_DIR="${KMN_DIR}"
   APP_DIR="${APP_DIR}" . "${APP_DIR}/app/env"
 
-  local cmdname=$1; shift
-  if type "kmn__$cmdname" >/dev/null 2>&1; then
-    "kmn__$cmdname" "$@"
-  else
-    command kmn "$cmdname" "$@" # call the **real** kmn command
-  fi
-}
+function __add() (
 
-# if invoked as a script rather than sourced, call function named on argv via the below;
-# note that this must be the first operation other than a function definition
-# for $_ to successfully distinguish between sourcing and invocation:
-[[ $_ != $0 ]] && return
+  # if [[ ${#} == 0 ]]; then
+  #     decrypt_help;
+  # fi
 
-echo "test 1"
-# make sure we actually *did* get passed a valid function name
-if declare -f "kmn__$1" >/dev/null 2>&1; then
-  echo "2 $@"
-  # invoke that function, passing arguments through
-  "$@" # same as "$1" "$2" "$3" ... for full argument list
-else
-  echo "Function $1 not recognized" >&2
-  exit 1
-fi
+  ################################################################################
+  # arguments
+
+  function parse_opts() {
+
+    while [ ${#} -gt 0 ]; do
+      case "$1" in
+        -- ) break ;;
+        -k | --key-name ) opts[KEY_NAME]="${2:?$ERR_MSG}" ; shift 2 ;;
+        -d | --dir ) opts[s]="${2:?$ERR_MSG}" ; shift 2 ;;
+        -* ) echo >&2 "$0: Error in usage." ; exit 1 ;;
+        * )  break ;;
+      esac
+    done
+
+    args=("$@")
+  }
+
+  declare args
+  declare -A opts
+  parse_opts $@
+
+  ################################################################################
+  # body
+
+  local pubkey_path="${HOME}/.ssh/${opts[KEY_NAME]}.pub"
+  echo $pubkey_path
+  # # TODO: assure it's public, not private
+  # cp "${pubkey_path}" "${PUBKEY_DIR}/pub/"
+
+  # (cd "${PUBKEY_DIR}" &&
+  #     git add --all . &&
+  #     git commit -m "${KEY_NAME}";
+  #     git push)
+
+  exit 0;
+)
+
+function main() (
+
+  # if (( ${#} == 0 )); then
+  #   main_help 0;
+  # fi
+
+  ################################################################################
+  # arguments
+
+  function parse_opts() {
+
+    while [ ${#} -gt 0 ]; do
+      case "$1" in
+        -- ) break ;;
+        # -c | --center ) opts[c]="$2" ; shift 2 ;;
+        # -V | --version ) version ; exit 0 ;;
+        -* ) echo >&2 "$0: Error in usage." ; exit 1 ;;
+        * )  break ;;
+      esac
+    done
+
+    args=("$@")
+  }
+
+  declare args
+  declare -A opts
+  parse_opts $@
+
+  ################################################################################
+  # body
+
+  ################################################################################
+  # caller
+
+  case "${args[0]}" in
+    keygen ) __keygen "${args[@]:1}" ;;
+    add ) __add "${args[@]:1}" ;;
+    * )
+      echo >&2 "Unknown command: $1";
+      # main_help 1;
+      exit 1;
+    ;;
+  esac
+)
+
+main "$@"
