,

diff --git a/linux/gsh-add b/linux/gsh-add
--- a/linux/gsh-add
+++ b/linux/gsh-add
@@ -1,5 +1,21 @@
 #! /bin/bash
 
+OPTSTRING=":r:k:"
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    r)
+      GSH_GH_REPO_NAME="${OPTARG}"
+      ;;
+    k)
+      GSH_KEY_NAME="${OPTARG}"
+      ;;
+    ?)
+      echo "Invalid option: -${OPTARG}."
+      exit 1
+      ;;
+  esac
+done
+
 repo_local_path="${HOME}/pit/${GSH_GH_REPO_NAME}"
 key_pub_path="${HOME}/.ssh/${GSH_KEY_NAME}.pub"
 
diff --git a/linux/gsh-git-config b/linux/gsh-git-config
--- a/linux/gsh-git-config
+++ b/linux/gsh-git-config
@@ -1,5 +1,21 @@
 #! /bin/bash
 
+OPTSTRING=":u:e:"
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    u)
+      GSH_GIT_USERNAME="${OPTARG}"
+      ;;
+    e)
+      GSH_GIT_EMAIL="${OPTARG}"
+      ;;
+    ?)
+      echo "Invalid option: -${OPTARG}."
+      exit 1
+      ;;
+  esac
+done
+
 # TODO: for windows '"C:/Program Files/OpenSSH/ssh.exe"'
 # TODO: or better for windows: where.exe ssh.exe
 # TODO: must be quoted due to spaces!
diff --git a/linux/gsh-github-ssh b/linux/gsh-github-ssh
--- a/linux/gsh-github-ssh
+++ b/linux/gsh-github-ssh
@@ -1,5 +1,18 @@
 #! /bin/bash
 
+OPTSTRING=":k:"
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    k)
+      GSH_KEY_NAME="${OPTARG}"
+      ;;
+    ?)
+      echo "Invalid option: -${OPTARG}."
+      exit 1
+      ;;
+  esac
+done
+
 key_pub_path="${HOME}/.ssh/${GSH_KEY_NAME}.pub"
 
 gh ssh-key add "${key_pub_path}" --type authentication
